project:
  type: website

website:
  title: "bill olander"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/olanderb
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

